name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/frontend.yml'
      - 'frontend/**/*'
      - '!frontend/.simple-git-hooks.json'
      - '!frontend/.lintstagedrc.json'
  pull_request:
    paths:
      - '.github/workflows/frontend.yml'
      - 'frontend/**/*'
      - '!frontend/.simple-git-hooks.json'
      - '!frontend/.lintstagedrc.json'

defaults:
  run:
    working-directory: frontend

jobs:
  testing:
    name: Test & Analysis
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Checkout Project Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use NodeJS LTS
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run check
      - name: Test
        run: npm run test:coverage
        env:
          CI: true
      - name: Collect Coverage
        run: |
          echo "${{ github.workspace }}/frontend"
          COVFILES=$(find packages -wholename '*/.coverage/lcov.info' | tr '\n' ',' | sed '$s/,$//')
          echo "COVFILES=$COVFILES" >> $GITHUB_ENV
      - name: Send Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ env.COVFILES }}
          flags: unittests
          fail_ci_if_error: true
          verbose: true
          working-directory: ${{ github.workspace }}/frontend
