name: Java CI

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/java.yml'
      - 'packages/java/**/*'
      - 'scripts/**/*'
      - 'pom.xml'
  pull_request:
    paths:
      - '.github/workflows/java.yml'
      - 'packages/java/**/*'
      - 'scripts/**/*'
      - 'pom.xml'

jobs:
  testing:
    name: Test & Analysis
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Checkout Project Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up OpenJDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Validate format
        run: mvn -B -am formatter:validate
      - name: Verify
        run: mvn -B -am verify
      - name: Collect Coverage
        run: |
          COVFILES=$(find packages/java -wholename 'target/site/jacoco/jacoco.xml' | tr '\n' ',' | sed '$s/,$//')
          echo "COVFILES=$COVFILES" >> $GITHUB_ENV
      - name: Send Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ env.COVFILES }}
          flags: unittests
          fail_ci_if_error: true
          root_dir: ${{ github.workspace }}
