name: Release

on:
  workflow_dispath:
    input:
      releaseVersion:
        description: Release Version
        required: true
      developmentVersion:
        description: Next Development Version
        required: true
job:
  releasing:
    name: Release
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Checkout Project Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Configure Git user
        run: |
          git config user.email "vaadin-bot@users.noreply.github.com"
          git config user.name "vaadin-bot"
      - name: Test release version
        run: | 
          echo "Release Version: ${{github.event.inputs.releaseVersion}}"
          echo "Next Development Version: ${{github.event.inputs.developmentVersion}}"