name: TypeScript Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        type: string
        required: true
        description: 'Version tag'

env:
  VERSION_TAG: ${{ github.event_name == 'release' && github.event.release.tag_name || github.event.inputs.tag_name }}
  BRANCH: ${{ github.ref_type == 'branch' && github.ref_name || 'main' }}

jobs:
  testing:
    name: Release
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Checkout Project Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ env.BRANCH }}
      - name: Verify Version Tag
        run: |
          git show-ref -q --tags $VERSION_TAG || { \
            echo "::error::$VERSION_TAG is not a valid tag" 1>&2;
            false; }
      - name: Use NodeJS LTS
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run check
      - name: Test
        run: npm run test
        env:
          CI: true
      - name: Bump New Version
        run: ./scripts/bump/exec.sh
        env:
          GIT_RELEASE_TOKEN: ${{ secrets.GIT_RELEASE_TOKEN }}
          REPO: ${{ github.repository }}
      - name: Re-build New Version
        run: npm run build
      - name: Publish
        run: |
          npx lerna publish from-package --yes --dist-tag \
            "$([[ $VERSION_TAG =~ alpha|beta|rc ]] && echo "next" || echo "latest")"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
